export { default as Lenis } from './lenis'
export { default as ScrollBar } from './scrollbar'
export { default as Nav } from './nav'
export { default as About } from './about'
export { default as Masonary } from './masonary'
